title: Hello, world! I'm Marko Milić
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://constantine2nd.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Marko Milić # add your name
author-img: marko-milic.jpg # add your photo
about-author: I am a software developer focusing on a security. Always happy to implement good design. # add description
social-x: milic_marko # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: constantine2nd # add your Github handle
social-linkedin: marko-milić-4332a81b9 # add your Linkedin handle
social-email: marko.milic@yahoo.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
